apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: inventory
    template: postgresql-persistent-template
  name: inventory-database
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi